services:
  Blanco-mysql:
    image: mysql:latest
    container_name: Blanco_mysql
    environment:
      MYSQL_DATABASE: Blanco_DB
      MYSQL_ALLOW_EMPTY_PASSWORD: yes
      MYSQL_USER: Blanco_DB_user
      MYSQL_PASSWORD: Blanco_DB_password
    ports:
      - "3307:3306"
    volumes:
      - Blanco_DB_data:/var/lib/mysql
    restart: unless-stopped
    networks:
      - service-communication
    healthcheck:
      test: [ "CMD", "mysqladmin" ,"ping", "-h", "localhost" ]
      timeout: 20s
      retries: 10

  Blanco-db-service:
    image: blanco-db-service
    container_name: Blanco_db
    build:
      context: DatabaseService
      dockerfile: Dockerfile
    ports:
      - "8081:8080"
    depends_on:
      Blanco-mysql:
        condition: service_healthy
        restart: true
    networks:
      - service-communication

networks:
  service-communication:

volumes:
  Blanco_DB_data: