services:
  Blanco-mysql:
    image: mysql:latest
    container_name: Blanco_mysql
    environment:
      MYSQL_DATABASE: Blanco_DB
      MYSQL_ALLOW_EMPTY_PASSWORD: yes
      MYSQL_USER: Blanco_DB_user
      MYSQL_PASSWORD: Blanco_DB_password
    ports:
      - "3307:3306"
    volumes:
      - Blanco_DB_data:/var/lib/mysql
    restart: unless-stopped
    networks:
      - service-communication
    healthcheck:
      test: [ "CMD", "mysqladmin" ,"ping", "-h", "localhost" ]
      timeout: 20s
      retries: 10


  Blanco-database-service:
    image: blanco-db-service
    container_name: Blanco_DatabaseService
    build:
      context: DatabaseService
      dockerfile: Dockerfile
    ports:
      - "8081:8080"
    depends_on:
      Blanco-mysql:
        condition: service_healthy
        restart: true
    networks:
      - service-communication


  Blanco-authentication-service:
    image: blanco-authentication-service
    container_name: Blanco_AuthenticationService
    build:
      context: AuthenticationService
      dockerfile: Dockerfile
    ports:
      - "8082:8080"
    depends_on:
      - Blanco-database-service
    networks:
      - service-communication


  Blanco-MoneyManagementService:
    image: blanco-money-management-service
    container_name: Blanco_MoneyManagementService
    build:
      context: MoneyManagementService
      dockerfile: Dockerfile
    ports:
      - "8083:8080"
    depends_on:
      - Blanco-database-service
    networks:
      - service-communication


  Blanco-AnalyticsService:
    image: blanco-analytics-service
    container_name: Blanco_AnalyticsService
    build:
      context: AnalyticsService
      dockerfile: Dockerfile
    ports:
      - "8084:8080"
    depends_on:
      - Blanco-database-service
    networks:
      - service-communication


  Blanco-NotificationService:
    image: blanco-notification-service
    container_name: Blanco_NotificationService
    build:
      context: NotificationService
      dockerfile: Dockerfile
    ports:
      - "8085:8080"
    depends_on:
      - Blanco-database-service
    networks:
      - service-communication


networks:
  service-communication:

volumes:
  Blanco_DB_data: