services:
  Blanco-mysql:
    image: mysql:latest
    container_name: Blanco-mysql
    environment:
      MYSQL_DATABASE: Blanco_DB
      MYSQL_ALLOW_EMPTY_PASSWORD: yes
      MYSQL_USER: Blanco_DB_user
      MYSQL_PASSWORD: Blanco_DB_password
    ports:
      - "3307:3306"
    volumes:
      - Blanco_DB_data:/var/lib/mysql
    restart: unless-stopped
    networks:
      - service-communication
    healthcheck:
      test: [ "CMD", "mysqladmin" ,"ping", "-h", "localhost" ]
      timeout: 20s
      retries: 10


  Blanco-database-service:
    image: blanco-db-service
    container_name: Blanco-Database-Service
    build:
      context: DatabaseService
      dockerfile: Dockerfile
    ports:
      - "8081:8081"
    depends_on:
      Blanco-mysql:
        condition: service_healthy
        restart: true
    networks:
      - service-communication


  Blanco-authentication-service:
    image: blanco-authentication-service
    container_name: Blanco-Authentication-Service
    build:
      context: AuthenticationService
      dockerfile: Dockerfile
    ports:
      - "8082:8082"
    depends_on:
      - Blanco-database-service
    networks:
      - service-communication


  Blanco-MoneyManagementService:
    image: blanco-money-management-service
    container_name: Blanco-Money-Management-Service
    build:
      context: MoneyManagementService
      dockerfile: Dockerfile
    ports:
      - "8083:8083"
    depends_on:
      - Blanco-database-service
    networks:
      - service-communication


  Blanco-AnalyticsService:
    image: blanco-analytics-service
    container_name: Blanco-Analytics-Service
    build:
      context: AnalyticsService
      dockerfile: Dockerfile
    ports:
      - "8084:8084"
    depends_on:
      - Blanco-database-service
    networks:
      - service-communication


  Blanco-NotificationService:
    image: blanco-notification-service
    container_name: Blanco-Notification-Service
    build:
      context: NotificationService
      dockerfile: Dockerfile
    ports:
      - "8085:8085"
    depends_on:
      - Blanco-database-service
    networks:
      - service-communication


  Blanco-APIManagerService:
    image: blanco-api-manager-service
    container_name: Blanco-API-Manager-Service
    build:
      context: APIManagerService
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - Blanco-database-service
      - Blanco-authentication-service
      - Blanco-MoneyManagementService
      - Blanco-NotificationService
      - Blanco-AnalyticsService
    networks:
      - service-communication


networks:
  service-communication:

volumes:
  Blanco_DB_data: